package com.alkaid.dtmp.attendance.dao.mapper;

import com.alkaid.dtmp.attendance.dao.model.WorkOvertime;
import com.alkaid.dtmp.attendance.dao.model.WorkOvertimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkOvertimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_work_overtime
     *
     * @mbg.generated
     */
    long countByExample(WorkOvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_work_overtime
     *
     * @mbg.generated
     */
    int deleteByExample(WorkOvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_work_overtime
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer workovertimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_work_overtime
     *
     * @mbg.generated
     */
    int insert(WorkOvertime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_work_overtime
     *
     * @mbg.generated
     */
    int insertSelective(WorkOvertime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_work_overtime
     *
     * @mbg.generated
     */
    List<WorkOvertime> selectByExample(WorkOvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_work_overtime
     *
     * @mbg.generated
     */
    WorkOvertime selectByPrimaryKey(Integer workovertimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_work_overtime
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WorkOvertime record, @Param("example") WorkOvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_work_overtime
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WorkOvertime record, @Param("example") WorkOvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_work_overtime
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WorkOvertime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_work_overtime
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WorkOvertime record);
}