#DUBBOX
dubbox:
  application:
    name: dtmp-redis-service
    organization: dubbox
    owner: alkaid
  registry:
    protocol: zookeeper
    address: 192.168.43.150:2181
  annotation:
    package: com.alkaid.dtmp.redis.service.impl
  protocol:
    name: dubbo
    port: 20883
    host: 192.168.127.1
    timeout: 30000
    threadpool: fixed
    threads: 500
    accepts: 1000
    serialization: kryo
    optimizer: com.alkaid.dtmp.redis.common.serial.ServiceOptimizerImpl
  monitor:
    enabled: false
    address: 127.0.0.1:6060
    username: admin
    password: admin

spring:
  redis:
    database: 0
    host: 192.168.43.150
    port: 6379
    password: 123456
    timeout: 10000
    pool:
      max-active: 500
      max-wait: 10000
      max-idle: 100


