server:
  port: 9003

#DUBBO
dubbox:
  application:
    name: dtmp-attendance-web
    organization: dubbox
    owner: alkaid
  protocol:
    name: dubbo
    port: 20883
    host: 127.0.0.1
  registry:
    protocol: zookeeper
    address: 192.168.43.150:2181
  annotation:
    package: com.alkaid.dtmp.attendance.web.controller
  monitor:
    enabled: false
    address: 127.0.0.1:6060
    username: admin
    password: admin

